ALTER TABLE schools ADD COLUMN IF NOT EXISTS subdomain VARCHAR(63) UNIQUE;
ALTER TABLE schools ADD COLUMN IF NOT EXISTS custom_domain VARCHAR(255) UNIQUE;
ALTER TABLE schools ADD COLUMN IF NOT EXISTS logo_url TEXT;
ALTER TABLE schools ADD COLUMN IF NOT EXISTS brand_color VARCHAR(7);
ALTER TABLE schools ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'active'
  CHECK (status IN ('pending', 'active', 'suspended', 'rejected'));
ALTER TABLE schools ADD COLUMN IF NOT EXISTS contact_name VARCHAR(255);
ALTER TABLE schools ADD COLUMN IF NOT EXISTS contact_email VARCHAR(255);
ALTER TABLE schools ADD COLUMN IF NOT EXISTS rejection_reason TEXT;

CREATE TABLE IF NOT EXISTS platform_admins (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);